import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatINR, formatDateTime } from "../utils/formatters";
import { logAudit } from "./auditService";
import type { UserProfile, YearWiseStatsModel } from "../types";

export interface ClassReportRow {
  class: string;
  department: string;
  year: number;
  totalStudents: number;
  fullyPaid: number;
  partiallyPaid: number;
  pending: number;
  exempted: number;
  totalRequired: number;
  totalReceived: number;
  totalOutstanding: number;
  collectionPercentage: string;
}

export async function exportClassReportExcel(
  eventName: string,
  data: ClassReportRow[],
  user: UserProfile
) {
  const wsData = [
    [`EKCTC Finance - Class-wise Collection Report`],
    [`Event: ${eventName}`],
    [`Generated by: ${user.name} (${user.role}) on ${formatDateTime(new Date())}`],
    [],
    [
      "Class",
      "Department",
      "Year",
      "Total Students",
      "Fully Paid",
      "Partially Paid",
      "Pending",
      "Exempted",
      "Required (INR)",
      "Received (INR)",
      "Outstanding (INR)",
      "Collection %",
    ],
    ...data.map((r) => [
      r.class,
      r.department,
      r.year,
      r.totalStudents,
      r.fullyPaid,
      r.partiallyPaid,
      r.pending,
      r.exempted,
      r.totalRequired,
      r.totalReceived,
      r.totalOutstanding,
      r.collectionPercentage,
    ]),
  ];

  const ws = XLSX.utils.aoa_to_sheet(wsData);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Class Report");
  XLSX.writeFile(wb, `${eventName.replace(/\s+/g, "_")}_Class_Report.xlsx`);

  await logAudit({
    userId: user.uid,
    userRole: user.role,
    userName: user.name,
    action: "export_excel_class_report",
    category: "report_export",
    description: `Exported Excel class report for event "${eventName}"`,
  });
}

export async function exportClassReportPDF(
  eventName: string,
  data: ClassReportRow[],
  user: UserProfile
) {
  const doc = new jsPDF({ orientation: "landscape" });

  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text("EKCTC Finance - Class Collection Report", 14, 15);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Event: ${eventName} | Generated by: ${user.name} | ${formatDateTime(new Date())}`, 14, 22);

  const tableRows = data.map((r) => [
    r.class,
    r.department,
    r.year.toString(),
    r.totalStudents.toString(),
    r.fullyPaid.toString(),
    r.partiallyPaid.toString(),
    r.pending.toString(),
    r.exempted.toString(),
    formatINR(r.totalRequired),
    formatINR(r.totalReceived),
    formatINR(r.totalOutstanding),
    r.collectionPercentage,
  ]);

  autoTable(doc, {
    startY: 28,
    head: [[
      "Class",
      "Dept",
      "Yr",
      "Total",
      "Full",
      "Part",
      "Pend",
      "Exempt",
      "Required",
      "Received",
      "Outstanding",
      "%",
    ]],
    body: tableRows,
    theme: "grid",
    headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 8, cellPadding: 3 },
  });

  doc.save(`${eventName.replace(/\s+/g, "_")}_Class_Report.pdf`);

  await logAudit({
    userId: user.uid,
    userRole: user.role,
    userName: user.name,
    action: "export_pdf_class_report",
    category: "report_export",
    description: `Exported PDF class report for event "${eventName}"`,
  });
}

export async function exportYearWiseExcel(
  eventName: string,
  data: YearWiseStatsModel[],
  user: UserProfile
) {
  const wsData = [
    [`EKCTC Finance - Year-Wise Collection & Status Report`],
    [`Event: ${eventName}`],
    [`Generated by: ${user.name} (${user.role}) on ${formatDateTime(new Date())}`],
    [],
    [
      "Academic Batch",
      "Total Students",
      "Fully Paid / Settled",
      "Partially Paid",
      "Pending",
      "Exempted",
      "Target (INR)",
      "Collected (INR)",
      "Remaining (INR)",
      "Collection %",
    ],
    ...data.map((r) => [
      r.yearLabel,
      r.totalStudents,
      r.settledCount,
      r.partiallyPaidCount,
      r.pendingCount,
      r.exemptedCount,
      r.totalTarget,
      r.totalCollected,
      r.remainingBalance,
      `${r.collectionPercentage}%`,
    ]),
  ];

  const ws = XLSX.utils.aoa_to_sheet(wsData);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Year Report");
  XLSX.writeFile(wb, `${eventName.replace(/\s+/g, "_")}_Year_Report.xlsx`);

  await logAudit({
    userId: user.uid,
    userRole: user.role,
    userName: user.name,
    action: "export_excel_year_report",
    category: "report_export",
    description: `Exported Excel year-wise report for event "${eventName}"`,
  });
}

export async function exportYearWisePDF(
  eventName: string,
  data: YearWiseStatsModel[],
  user: UserProfile
) {
  const doc = new jsPDF({ orientation: "landscape" });

  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text("EKCTC Finance - Year-Wise Collection Report", 14, 15);

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Event: ${eventName} | Generated by: ${user.name} | ${formatDateTime(new Date())}`, 14, 22);

  const tableRows = data.map((r) => [
    r.yearLabel,
    r.totalStudents.toString(),
    r.settledCount.toString(),
    r.partiallyPaidCount.toString(),
    r.pendingCount.toString(),
    r.exemptedCount.toString(),
    formatINR(r.totalTarget),
    formatINR(r.totalCollected),
    formatINR(r.remainingBalance),
    `${r.collectionPercentage}%`,
  ]);

  autoTable(doc, {
    startY: 28,
    head: [[
      "Academic Batch",
      "Total",
      "Fully Paid",
      "Partially Paid",
      "Pending",
      "Exempted",
      "Target",
      "Collected",
      "Remaining",
      "%",
    ]],
    body: tableRows,
    theme: "grid",
    headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 9, cellPadding: 4 },
  });

  doc.save(`${eventName.replace(/\s+/g, "_")}_Year_Report.pdf`);

  await logAudit({
    userId: user.uid,
    userRole: user.role,
    userName: user.name,
    action: "export_pdf_year_report",
    category: "report_export",
    description: `Exported PDF year-wise report for event "${eventName}"`,
  });
}

export async function exportEventDataJSON(
  eventName: string,
  eventData: Record<string, any>,
  user: UserProfile
) {
  const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(eventData, null, 2));
  const downloadAnchor = document.createElement("a");
  downloadAnchor.setAttribute("href", dataStr);
  downloadAnchor.setAttribute("download", `${eventName.replace(/\s+/g, "_")}_backup_${new Date().toISOString().slice(0, 10)}.json`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();

  await logAudit({
    userId: user.uid,
    userRole: user.role,
    userName: user.name,
    action: "export_event_json_backup",
    category: "report_export",
    description: `Exported event data JSON backup for "${eventName}"`,
  });
}
